name: Website

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build
    - name: Prepare deployment directory
      run: |
        mkdir -p public
        cp -r result/* public/
    - uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public # Use the directory you just created
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
